import { ToDoItem } from "./toDoItem";
import { appendToDoItems, projectNameInput } from "./domManipulation";
import { Project, projects } from "./project";
// import { toDoList } from "./domManipulation";
let toDoItem = new ToDoItem("Default list item", `2022-06-30`, false);
let defaultProject = new Project("defaultProject");
defaultProject.addItem(toDoItem);
projects.addProject(defaultProject);
// const appendToDoItems = (projectNumber) => {
//   const toDoItemsArr = projects.projectArr[projectNumber].toDoItems;
//   toDoItemsArr.forEach((toDoItem) => {
//     const listItem = document.createElement("div");
//     listItem.classList.add("listItem");
//     const checkbox = document.createElement("input");
//     checkbox.setAttribute("type", "checkbox");
//     checkbox.checked = toDoItem.isComplete;
//     const description = document.createElement("div");
//     description.classList.add("description");
//     description.textContent = toDoItem.description;
//     const dueDate = document.createElement("div");
//     dueDate.classList.add("dueDate");
//     dueDate.textContent = `Due date: ${toDoItem.dueDate}`;
//     const deleteButton = document.createElement("button");
//     deleteButton.classList.add("deleteButton");
//     deleteButton.textContent = "X";
//     listItem.append(checkbox, description, dueDate, deleteButton);
//     toDoList.appendChild(listItem);
//   });
// };
appendToDoItems(0);
